version: "3.8"
services:
  db:
    image: postgres
    container_name: tma_db
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: expert
      POSTGRES_PASSWORD: expert
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: tma_admin_db
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tma@tma.pl
      PGADMIN_DEFAULT_PASSWORD: tma

