spring:
  config:
    activate:
      on-profile: dev-local
  datasource:
    url: jdbc:postgresql://localhost:5431/tma_db
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
