server:
  port: 8080

spring:
  application:
    name: TestManagement
  datasource:
    url: jdbc:postgresql://ep-shrill-frog-a2vjr7pk-pooler.eu-central-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_NmRYdTXexp14
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true