spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://db:5432/tma_db
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
<<<<<<< HEAD
server:
  port: 8080
jwt:
  expiration-time: 3600000 # 1 hour
  refresh-expiration-time: 2592000000 # 30 days
  secret-key: Smt3dWRyTDdXUEYzd3hTOWpIWG9GMUsrSzVOWHdRek42V1FjU1VrdXJZMmZ1aVpLWkN2b3p5MWNlTmhjM21XeQ==
google:
  client-id: 588964522027-upoq1puqhmac9dvbft659rm8tjk2jk1f.apps.googleusercontent.com # Replace with your actual Client ID
=======
>>>>>>> cba3a7d1317e702395c171d76a4107dbafe12c0e
